name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:latest ./backend
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest ./frontend
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: ${{ secrets.ACR_NAME }}
          containerAppName: ai-study-buddy
          resourceGroup: study-buddy-rg
          imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest
